<a href="https://colab.research.google.com/github/Smkale2232/pandas_practice/blob/main/notebook9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [4]:
arr = np.random.rand(4, 3)
print("Numpy array:")
print(arr)

Numpy array:
[[0.07682856 0.37663026 0.50948363]
 [0.95727197 0.46064889 0.98886635]
 [0.01158961 0.74004583 0.37892759]
 [0.63243516 0.28367464 0.40206521]]


In [3]:
# convert numpy array to dataframe
df = pd.DataFrame(arr, columns =['A', 'B', 'C'])
print("\nPandas DataFrame: ")
df


Pandas DataFrame: 


A         B         C
0  0.898024  0.736628  0.886583
1  0.748102  0.539355  0.988819
2  0.332604  0.185840  0.356962
3  0.248208  0.131532  0.834253